stages:
  - prep
  - deploy-infra
  - deploy-apps

allocate-subnet:
  stage: prep
  script:
    - echo "using subnet 123.123.123.0/24"

read-bom:
  stage: prep
  needs:
    - allocate-subnet
  script:
    - echo "read BoM"

deploy-infra-vault:
  stage: deploy-infra
  environment: prod
  image: hashicorp/terraform:1.10
  before_script:
    - echo "terraform init vault"
  script:
    - echo "terraform plan vault"
    - echo "terraform apply vault"

deploy-infra-aws:
  stage: deploy-infra
  environment: prod
  image: hashicorp/terraform:1.10
  variables:
    ROOT_PAT: glpat-RootUserToken1234!!!
  needs:
    - deploy-infra-vault
  before_script:
    - git config --global url."http://root:${ROOT_PAT}@gitlab.test.lab".insteadOf "http://gitlab.test.lab"
    - git clone http://root:${ROOT_PAT}@gitlab.test.lab/dev/environment/infrastructure.git
    - cd infrastructure/deploy
    - terraform init
  script:
    - terraform plan -out ${CI_PIPELINE_ID}-${CI_JOB_NAME_SLUG}.tfplan
    - terraform apply -auto-approve ${CI_PIPELINE_ID}-${CI_JOB_NAME_SLUG}.tfplan
